service: sms-marketing-api

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: dev

functions:
  api:
    handler: index.handler
    timeout: 30
    events:
      - httpApi: "*"

custom:
  serverless-offline:
    httpPort: 3000
    host: 0.0.0.0
